name: remote ssh command
on: 
  push:
    branches: [master]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: actions/checkout@v3
      with:
        host: 13.235.115.64
        username: ubuntu
        key: ${{ secrets.TEST_UBUNTU }}
        port: 22
  test:  
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    

