name: remote ssh command
on: 
  push:
    branches: [master]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: actions/checkout@v2
      with:
        host: 13.235.115.64
        username: ubuntu
        key: ${{ secrets.TEST_UBUNTU }}
        port: 22 
    - name: installaing java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven build
      run: mvn clean package
    - name: ls
      run: ls -la
    - name: change directory
      run: cp -r target /opt
    
    
      
  
    

