name: remote ssh command
on: 
  push:
    branches: [master]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 13.235.115.64
        username: ubuntu
        key: ${{ secrets.TEST_UBUNTU }}
        port: 22
        script: mkdir testing

