name: remote ssh command
on: 
  push:
    branches: [master]
jobs:

  build:
    name: Build
    runs-on: 
      - self-hosted
      - dev-env
    steps:
     - name: building the source code
       uses: actions/checkout@v2
       
     - name: maven build ww
       run: mvn clean package
     
     
  
    
      
  
    

