name: remote ssh command
on: 
  push:
    branches: [master]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 13.235.115.64
        username: ubuntu
        key: ${{ secrets.TEST_UBUNTU }}
        port: 22 
    - name: installaing java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      uses: actions/checkout@v2
      with:
       run: mvn -B package
    - name: ls
      run: ls -la
  
    

