name: remote ssh command
on: 
  push:
    branches: [master]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: actions/setup-java@v1
      with:
        host: 13.235.115.64
        username: ubuntu
        key: ${{ secrets.TEST_UBUNTU }}
        port: 22 
        java-version: 1.8
  
    

